using System;
using Volo.Abp.EventBus;
using Volo.Abp.MultiTenancy;

namespace Dignite.Abp.Notifications;

/// <summary>
/// A notification published in one process for the process that hosts the inbox and the channels to distribute. The
/// remote publisher (<c>Dignite.Abp.Notifications.Remote</c>) sends it instead of distributing locally;
/// <c>NotificationPublishRequestedHandler</c> in <c>Dignite.Abp.Notifications</c> hands it to that process's
/// distributor. One notification is one event, whatever the number of recipients.
/// </summary>
/// <remarks>
/// <para>
/// A server-side event that comes before distribution, at the same level as the distribution job's arguments: no
/// notifier or client ever sees it, which is why it may carry the recipient list that
/// <see cref="NotificationDeliveryRequestedEto"/> never does.
/// </para>
/// <para>
/// The same wire discipline as <see cref="NotificationDeliveryRequestedEto"/>: ABP's event bus (and its outbox/inbox)
/// serializes ETOs with plain System.Text.Json, without the application's <c>AbpSystemTextJsonSerializerOptions</c>,
/// so every member stays default-STJ round-trippable and the payload travels pre-serialized in <see cref="DataJson"/>.
/// </para>
/// <para>
/// Implements <see cref="IMultiTenant"/> rather than <see cref="IEventDataMayHaveTenantId"/>: the receiving event bus
/// then runs the handler in <see cref="TenantId"/> even when it is <see langword="null"/> (host), instead of falling
/// back to whatever tenant is ambient.
/// </para>
/// </remarks>
[EventName("Dignite.Abp.Notifications.NotificationPublishRequested")]
[Serializable]
public class NotificationPublishRequestedEto : IMultiTenant
{
    /// <summary>Generated by the publisher; it becomes the notification's id in the inbox, so it is the idempotency key.</summary>
    public Guid NotificationId { get; set; }

    /// <summary>The notification's tenant; <see langword="null"/> is the host.</summary>
    public Guid? TenantId { get; set; }

    public string NotificationName { get; set; } = default!;

    /// <summary>
    /// The payload as discriminator-tagged JSON produced by <see cref="INotificationDataSerializer"/> in the publishing
    /// process (e.g. <c>{"type":"Dignite.Message","message":"..."}</c>), or null when the notification carries no data.
    /// The receiving process stores and forwards it as it is, so it needs to know the payload type only to render it
    /// itself (as the Email and Push notifiers do).
    /// </summary>
    public string? DataJson { get; set; }

    public NotificationSeverity Severity { get; set; }

    /// <summary>Stable name of the entity the notification is about, never a CLR type name.</summary>
    public string? EntityTypeName { get; set; }

    public string? EntityId { get; set; }

    public DateTime CreationTime { get; set; }

    /// <summary>
    /// <see langword="null"/> resolves recipients from subscriptions; an empty array is a no-op; a non-empty array lists
    /// the recipients as the caller passed them (duplicates included — the receiver normalizes them).
    /// </summary>
    public Guid[]? UserIds { get; set; }

    public Guid[]? ExcludedUserIds { get; set; }

    /// <summary>
    /// The external channels, already resolved by the publisher, where the routing rules of the module that defines the
    /// notification are configured. <see langword="null"/> (or empty) means inbox-only.
    /// </summary>
    public string[]? Channels { get; set; }
}
