// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.NotificationCenter;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.NotificationCenter;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(INotificationSubscriptionAppService), typeof(NotificationSubscriptionClientProxy))]
public partial class NotificationSubscriptionClientProxy : ClientProxyBase<INotificationSubscriptionAppService>, INotificationSubscriptionAppService
{
    public virtual async Task<ListResultDto<NotificationSubscriptionDto>> GetSubscriptionsAsync()
    {
        return await RequestAsync<ListResultDto<NotificationSubscriptionDto>>(nameof(GetSubscriptionsAsync));
    }

    public virtual async Task SubscribeAsync(NotificationSubscriptionScopeDto input)
    {
        await RequestAsync(nameof(SubscribeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(NotificationSubscriptionScopeDto), input }
        });
    }

    public virtual async Task UnsubscribeAsync(NotificationSubscriptionScopeDto input)
    {
        await RequestAsync(nameof(UnsubscribeAsync), new ClientProxyRequestTypeValue
        {
            { typeof(NotificationSubscriptionScopeDto), input }
        });
    }
}
