// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.NotificationCenter;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.NotificationCenter;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IPushDeviceAppService), typeof(PushDeviceClientProxy))]
public partial class PushDeviceClientProxy : ClientProxyBase<IPushDeviceAppService>, IPushDeviceAppService
{
    public virtual async Task RegisterAsync(PushDeviceInput input)
    {
        await RequestAsync(nameof(RegisterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PushDeviceInput), input }
        });
    }

    public virtual async Task UnregisterAsync(PushDeviceInput input)
    {
        await RequestAsync(nameof(UnregisterAsync), new ClientProxyRequestTypeValue
        {
            { typeof(PushDeviceInput), input }
        });
    }
}
