// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using Dignite.NotificationCenter;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Http.Modeling;

// ReSharper disable once CheckNamespace
namespace Dignite.NotificationCenter;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IUserNotificationAppService), typeof(UserNotificationClientProxy))]
public partial class UserNotificationClientProxy : ClientProxyBase<IUserNotificationAppService>, IUserNotificationAppService
{
    public virtual async Task<PagedResultDto<UserNotificationDto>> GetListAsync(GetUserNotificationListInput input)
    {
        return await RequestAsync<PagedResultDto<UserNotificationDto>>(nameof(GetListAsync), new ClientProxyRequestTypeValue
        {
            { typeof(GetUserNotificationListInput), input }
        });
    }

    public virtual async Task<int> GetUnreadCountAsync()
    {
        return await RequestAsync<int>(nameof(GetUnreadCountAsync));
    }

    public virtual async Task MarkAsReadAsync(Guid notificationId)
    {
        await RequestAsync(nameof(MarkAsReadAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), notificationId }
        });
    }

    public virtual async Task MarkAllAsReadAsync()
    {
        await RequestAsync(nameof(MarkAllAsReadAsync));
    }

    public virtual async Task DeleteAsync(Guid notificationId)
    {
        await RequestAsync(nameof(DeleteAsync), new ClientProxyRequestTypeValue
        {
            { typeof(Guid), notificationId }
        });
    }

    public virtual async Task DeleteAllReadAsync()
    {
        await RequestAsync(nameof(DeleteAllReadAsync));
    }
}
